### PR TITLE
Add travis-ci config file

### PR DESCRIPTION
**Pull request by catbieber**
Configuration to build pushes/pull requests via travis-ci.

### CODE REVIEW

**Comment by mandragorn** [comment]
+2 - I was wondering why this was failing when I just tried to merge a pull request.

**Comment by kentmw** [comment]
Neat stuff. Does travis run on iOS? Saw some brew stuff in there.

**Comment by catbieber** [comment]
It does Linux and OSX, there's a separate PR for Appveyor which does Windows.

**Comment by mandragorn** [comment]
merging this cuz I want tests to run on commit...

**Pull request merged**
