### PR TITLE
Added the ability for ListView Children to use different ChildViews

### PR DESCRIPTION
**Pull request by patrickckelly**
Added a method to ListView that can be overridden to allow Children to use different views. I am not sure if the method should be prefaced by "_", "__" or neither.

### CODE REVIEW

**Comment by arikwex** [comment]
Looks good.  I think we'd want this merged in to 0.1.x branch as well though.

**Comment by patrickckelly** [comment]
Is that something I should do on my end?

**Comment by kentmw** [comment]
@patrickckelly, are you still working on this or would you like @mandragorn or me to take over?

**Comment by patrickckelly** [comment]
I am still working on it for master, I should have it done by Sunday. Should this be version be rebased for 0.1.x?

**Comment by kentmw** [comment]
@patrickckelly, do you want to finish this patch? If I don't hear from you in a week, I'll just finish it for you.

**Comment by kentmw** [comment]
handled in another pull request

**Pull request closed without merging**
