### PR TITLE
 #336 - DataBehavior update when to skip retrieval

### PR DESCRIPTION
**Pull request by mandragorn**
There are times when object retrieval isn't required and the
'fetched' event is undesirable.
* When the current ids is empty/undefined/null and the new ids is
  empty/undefined/null.
* When the function defining the ids returns something that indicates
  that ids shouldn't be updated and objects shouldn't be fetched.
  { skipObjectRetrieval: true }

### CODE REVIEW

**Comment by mandragorn** [comment]
@kentmw - this was the last one I had queued up for DataBehavior and is the one that I'm least sure of.  Let me know what you think.

**Comment by mandragorn** [comment]
2nd push is just a rebase after merging the other pull request.

**Comment by mandragorn** [comment]
can you point out where I can make the code easier to read?

**Comment by kentmw** [comment]
I tried. It's just one of those problems where what we want to do is complex and the code for databehavior itself is complex. So when we add more to it, it already starts off with a cloudy feeling. It's some awesome functionality, just the immense duck typing makes it hard to understand at first glance - i.e. there's twice as much duck typing, edge catching, and helper method code than core logic code.

My only thoughts on how to help is to refactor utility/helper functions out of this class. Also, I can't tell if making more general method name would help or hurt (i.e. `_skipRetrieveOnEmptyTrackedIdsAndNewIds` being `_skipRetrieveCheck`)

**Comment by mandragorn** [comment]
ok, I'll merge for now and work on readability later.

**Pull request merged**
